[build]
  # Build command for the frontend
  command = "npm ci --legacy-peer-deps && npm run build"
  # Publish directory (where the built files are)
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "20"

# API redirects to Netlify functions
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/businesses"
  to = "/.netlify/functions/businesses-get"
  status = 200
  conditions = {Method = ["GET"]}

[[redirects]]
  from = "/api/businesses"
  to = "/.netlify/functions/businesses-create"
  status = 200
  conditions = {Method = ["POST"]}

[[redirects]]
  from = "/api/businesses/:id"
  to = "/.netlify/functions/businesses-update"
  status = 200
  conditions = {Method = ["PUT"]}

[[redirects]]
  from = "/api/businesses/:id/vote"
  to = "/.netlify/functions/businesses-vote"
  status = 200

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events-get"
  status = 200
  conditions = {Method = ["GET"]}

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events-create"
  status = 200
  conditions = {Method = ["POST"]}

[[redirects]]
  from = "/api/events/:id"
  to = "/.netlify/functions/events-delete"
  status = 200
  conditions = {Method = ["DELETE"]}

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache index.html for a shorter time
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

